export enum localStorageTypes {
    SET_USER_LOGGED_REQUEST = "SET_USER_LOGGED_REQUEST",
    SET_USER_LOGGED_SUCCESS = "SET_USER_LOGGED_SUCCESS",
    SET_USER_LOGGED_FAILURE = "SET_USER_LOGGED_FAILURE",

    SET_FAVORITE_HOTELS_REQUEST = "SET_FAVORITE_HOTELS_REQUEST",
    SET_FAVORITE_HOTELS_SUCCESS = "SET_FAVORITE_HOTELS_SUCCESS",
    SET_FAVORITE_HOTELS_FAILURE = "SET_FAVORITE_HOTELS_FAILURE"
}